version: '{build}'
os: Windows Server 2012
clone_depth: 10
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0
build_script:
  - cmd: mvn clean package -q --batch-mode -DskipTests -DfinalName=sharpen
test_script:
  - cmd: mvn -DfinalName=sharpen test -q
after_test:
  - cmd: mvn install -q -Pqulice -DskipTests -DfinalName=sharpen > code_quality_report.txt || exit /B 0
artifacts: 
  - path: src\target\sharpen-jar-with-dependencies.jar
    name: sharpen-with-dependencies

  - path: code_quality_report.txt
    name: Code quality messages
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2


